# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    # Strict rules (real errors)
    missing_required_param: error
    invalid_null_aware_operator: error
    # Treat these as warnings initially
    use_build_context_synchronously: warning
    avoid_void_async: warning

linter:
  rules:
    # Relax some rules for now
    prefer_const_constructors: warning  # Change from error to warning
    avoid_redundant_argument_values: warning
    prefer_final_locals: warning
    non_constant_identifier_names: warning

    # Keep these enabled
    avoid_print: error
    unnecessary_import: error
    unused_import: error
    deprecated_member_use: warning